afdo_tools: fix script output for stable channel
We only search the current branch number for profiles on stable. Don't
print that we searched other branches.

BUG=b:322182978
TEST=Ran the script; error message is now more accurate

Change-Id: I1bca9a0324a2ee694ea480938562b826f8ea25eb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/5362319
Tested-by: George Burgess <gbiv@chromium.org>
Commit-Queue: George Burgess <gbiv@chromium.org>
Reviewed-by: Ryan Beltran <ryanbeltran@chromium.org>

diff --git a/afdo_tools/update_kernel_afdo b/afdo_tools/update_kernel_afdo
--- a/afdo_tools/update_kernel_afdo
+++ b/afdo_tools/update_kernel_afdo
@@ -257,8 +257,14 @@ do
       fi
       if [[ -z "${latest}" ]]
       then
-        echo "ERROR: No M${curr_branch_number}, M${prev_branch} profiles in\
+        if [[ "${channel}" == "stable" ]]
+        then
+          echo "ERROR: No M${curr_branch_number} profiles in\
  ${arch_gsbase[${arch}]}/${kver}/" >&2
+        else
+          echo "ERROR: No M${curr_branch_number}, M${prev_branch} profiles in\
+ ${arch_gsbase[${arch}]}/${kver}/" >&2
+        fi
         echo "Skipping ${arch}/${kver}" >&2
         errs="${errs} ${kver}"
         continue
