afdo_tools: print arch info when saying 'wrong version'
ATM, this script just prints the kernel version that something went
wrong on. This is unhelpful when only one of the two arches are failing.

BUG=b:322182978
TEST=None

Change-Id: I79e72dc9be9fe17a52f6b9ead8abae4f11c2ce8e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/toolchain-utils/+/5367066
Reviewed-by: Ryan Beltran <ryanbeltran@chromium.org>
Commit-Queue: George Burgess <gbiv@chromium.org>
Tested-by: George Burgess <gbiv@chromium.org>

diff --git a/afdo_tools/update_kernel_afdo b/afdo_tools/update_kernel_afdo
--- a/afdo_tools/update_kernel_afdo
+++ b/afdo_tools/update_kernel_afdo
@@ -276,8 +276,8 @@ do
       if [ "${file_time_unix}" -lt "${expected_time}" ]
       then
         expected=$(env TZ=UTC date +%Y-%m-%dT%H:%M:%SZ -d @"${expected_time}")
-        echo "ERROR: Wrong date for ${kver}: ${file_time} is before\
- ${expected}" >&2
+        echo "ERROR: Wrong date for ${arch_gsbase[${arch}]}/${kver}:\
+ ${file_time} is before\ ${expected}" >&2
         errs="${errs} ${kver}"
         continue
       fi
